**Creating matrices**
You can pass Python lists of lists to create a 2-D array (or “matrix”) to represent them in NumPy.

In [ ]:
import numpy as np 

data = np.array([[1, 2], [3, 4], [5, 6]])
data

array([[1, 2],
       [3, 4],
       [5, 6]])

**Indexing and slicing**

In [ ]:
data[0, 1]

2

In [ ]:
data[1:3]

In [ ]:
data[0:2, 0]

array([1, 3])

**aggregate matrices**

In [ ]:
data.max()

In [ ]:
data.min()

In [ ]:
data.sum()

**axis paramete**

In [ ]:
data = np.array([[1, 2], [5, 3], [4, 6]])
data.max(axis=0)

array([5, 6])

In [ ]:
data.max(axis=1)

array([2, 5, 6])

**add and multiply** matrices that have the same size.

In [ ]:
data = np.array([[1, 2], [3, 4]])
ones = np.array([[1, 1], [1, 1]])
data + ones

array([[2, 3],
       [4, 5]])

 if one matrix has only **one** column or **one** row, NumPy will use its broadcast rules for the operation.

In [ ]:
data = np.array([[1, 2], [3, 4], [5, 6]])
ones_row = np.array([[1, 1]])
data + ones_row

array([[2, 3],
       [4, 5],
       [6, 7]])

In [ ]:
np.ones(3)

array([1., 1., 1.])

In [ ]:
np.zeros(3)

array([0., 0., 0.])

In [ ]:
np.ones((3, 2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [ ]:
np.zeros((3, 2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [ ]:
np.ones((4, 3, 2))

array([[[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]]])

You can also use **random()** to create a 2D array if you give it a tuple describing the dimensions of the matrix:

In [ ]:
rng = np.random.default_rng(0)
rng.random((3, 2))

array([[0.63696169, 0.26978671],
       [0.04097352, 0.01652764],
       [0.81327024, 0.91275558]])