**Generating random numbers**

You can generate a 2 x 4 array of random integers between 0 and 4 with:

In [ ]:
import numpy as np
rng = np.random.default_rng(0)
rng.integers(5, size=(2, 4))

array([[4, 3, 2, 1],
       [1, 0, 0, 0]])

**How to get unique items and counts**

you can use np.unique to print the unique values in your array:

In [ ]:
a = np.array([11, 11, 12, 13, 14, 15, 16, 17, 12, 13, 11, 14, 18, 19, 20])
unique_values = np.unique(a)
unique_values

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

This also works with **2D** arrays! 

In [ ]:
a_2d = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [1, 2, 3, 4]])
unique_values = np.unique(a_2d)
unique_values

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

To find the unique **rows**, specify **axis=0** and for **columns**, specify **axis=1**.

In [ ]:
unique_rows = np.unique(a_2d, axis=0)
unique_rows

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

**Transposing and reshaping a matrix**

In [ ]:
data = np.array([[1, 2], [5, 3], [4, 6]])
data.reshape(2, 3)

array([[1, 2, 5],
       [3, 4, 6]])

In [ ]:
data.reshape(3, 2)

array([[1, 2],
       [5, 3],
       [4, 6]])

You can also **reverse** or change the axes of an array according to the values you specify.

In [ ]:
arr = np.arange(6).reshape((2, 3))
arr

array([[0, 1, 2],
       [3, 4, 5]])

In [ ]:
arr.transpose()

array([[0, 3],
       [1, 4],
       [2, 5]])

In [ ]:
arr.T

array([[0, 3],
       [1, 4],
       [2, 5]])